### ISSUE TITLE
BaaS selection

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/graphql-backend#5]
We need a database, and social authorization... what database service should we use? I’m using Firebase a lot these days and I would recommend that we consider using that, simply because it provides real time data and authorization.

We are open to ideas though. Any other recommendations?

**Comment by gwmccull** [comment]
I've never used Firebase so it'd be fun to learn it.  My other choice would be a Graph database (like Neo4J, Titan, or GraphDB) , but again, just because it'd be fun to learn

**Comment by MoonTahoe** [comment]
Yea. I'm down for whatever. I just don't want to use a BaaS graphql solution that doesn't let you define the queries or mutations. I was messing around with [scafold.io](https://scaphold.io/), and it was pretty cool, but they define the queries and mutations for you. Where is the fun in that?

**Comment by MoonTahoe** [comment]
I am going to be reviewing Graph Cool this week for an unrelated project. They have recently released a new version, and it may have everything that we need.
