### ISSUE TITLE
Schema Stitching

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/graphql-backend#9]
The point of using GraphQL is to have one gateway for all of our data needs. This project is possibly going to incorporate data from the Facebook API, our Graph DB, and even other social media apis. We need to begin to think about how we can make all of these schemas and APIs work together.  

Here is an [article](https://dev-blog.apollodata.com/graphql-schema-stitching-8af23354ac37) on schema stitching. I think we will require this technique. Thoughts??

**Comment by gwmccull** [comment]
Schema stitching sounds pretty cool

**Comment by MoonTahoe** [comment]
So Facebook's Graph is not publicly available...
